### ISSUE TITLE
Code for models

### ISSUE THREAD

**Issue by shubhamagarwal92** [satwikkottur/clevr-dialog#1]
Hi @satwikkottur 

Interesting work! Thanks for providing the scripts to generate the dataset. 

Could you also share the scripts related to the models that are used as baselines? 

Thanks in advance!

**Comment by satwikkottur** [comment]
Hello @shubhamagarwal92 ,

Thanks for your interest. The baseline models are based off these two repositories:
1. Visual Dialog Lua Code [[Github](https://github.com/batra-mlp-lab/visdial)]
2. CorefNMN Tensorflow Code [[Github](https://github.com/facebookresearch/corefnmn)]

The extensions are straight forward and mostly involve pre-processing scripts. While releasing these scripts is not currently planned, I will look into this in future. Apologies for the inconvenience.
